/**
 * Lookup statique de fiche technique pour les modèles courants.
 * Clé : "marque|modele" (insensible à la casse, espaces normalisés).
 */
export interface PhoneSpecSheet {
  processeur?: string;
  ecran_pouces?: string;
  ecran_type?: string;
  batterie_mah?: number;
  charge_w?: number;
  camera_principale?: string;
  camera_selfie?: string;
  sim_slots?: number;
  os?: string;
  nfc?: boolean;
}

const SPECS: Record<string, PhoneSpecSheet> = {
  // ── SAMSUNG ────────────────────────────────────────────────────────────────
  "samsung|galaxy s21": { processeur: "Exynos 2100 / Snapdragon 888", ecran_pouces: "6.2\"", ecran_type: "Dynamic AMOLED 120Hz", batterie_mah: 4000, charge_w: 25, camera_principale: "64 MP triple", camera_selfie: "10 MP", sim_slots: 2, os: "Android 11", nfc: true },
  "samsung|galaxy s21+": { processeur: "Exynos 2100 / Snapdragon 888", ecran_pouces: "6.7\"", ecran_type: "Dynamic AMOLED 120Hz", batterie_mah: 4800, charge_w: 25, camera_principale: "64 MP triple", camera_selfie: "10 MP", sim_slots: 2, os: "Android 11", nfc: true },
  "samsung|galaxy s21 ultra": { processeur: "Exynos 2100 / Snapdragon 888", ecran_pouces: "6.8\"", ecran_type: "Dynamic AMOLED 120Hz", batterie_mah: 5000, charge_w: 25, camera_principale: "108 MP quad", camera_selfie: "40 MP", sim_slots: 2, os: "Android 11", nfc: true },
  "samsung|galaxy s22": { processeur: "Exynos 2200 / Snapdragon 8 Gen 1", ecran_pouces: "6.1\"", ecran_type: "Dynamic AMOLED 120Hz", batterie_mah: 3700, charge_w: 25, camera_principale: "50 MP triple", camera_selfie: "10 MP", sim_slots: 2, os: "Android 12", nfc: true },
  "samsung|galaxy s22+": { processeur: "Exynos 2200 / Snapdragon 8 Gen 1", ecran_pouces: "6.6\"", ecran_type: "Dynamic AMOLED 120Hz", batterie_mah: 4500, charge_w: 45, camera_principale: "50 MP triple", camera_selfie: "10 MP", sim_slots: 2, os: "Android 12", nfc: true },
  "samsung|galaxy s22 ultra": { processeur: "Exynos 2200 / Snapdragon 8 Gen 1", ecran_pouces: "6.8\"", ecran_type: "Dynamic AMOLED 120Hz", batterie_mah: 5000, charge_w: 45, camera_principale: "108 MP quad", camera_selfie: "40 MP", sim_slots: 2, os: "Android 12", nfc: true },
  "samsung|galaxy s23": { processeur: "Snapdragon 8 Gen 2", ecran_pouces: "6.1\"", ecran_type: "Dynamic AMOLED 120Hz", batterie_mah: 3900, charge_w: 25, camera_principale: "50 MP triple", camera_selfie: "12 MP", sim_slots: 2, os: "Android 13", nfc: true },
  "samsung|galaxy s23+": { processeur: "Snapdragon 8 Gen 2", ecran_pouces: "6.6\"", ecran_type: "Dynamic AMOLED 120Hz", batterie_mah: 4700, charge_w: 45, camera_principale: "50 MP triple", camera_selfie: "12 MP", sim_slots: 2, os: "Android 13", nfc: true },
  "samsung|galaxy s23 ultra": { processeur: "Snapdragon 8 Gen 2", ecran_pouces: "6.8\"", ecran_type: "Dynamic AMOLED 120Hz", batterie_mah: 5000, charge_w: 45, camera_principale: "200 MP quad", camera_selfie: "12 MP", sim_slots: 2, os: "Android 13", nfc: true },
  "samsung|galaxy s23 fe": { processeur: "Exynos 2200 / Snapdragon 8 Gen 1", ecran_pouces: "6.4\"", ecran_type: "Dynamic AMOLED 120Hz", batterie_mah: 4500, charge_w: 25, camera_principale: "50 MP triple", camera_selfie: "10 MP", sim_slots: 2, os: "Android 13", nfc: true },
  "samsung|galaxy s24": { processeur: "Snapdragon 8 Gen 3", ecran_pouces: "6.2\"", ecran_type: "Dynamic AMOLED 120Hz", batterie_mah: 4000, charge_w: 25, camera_principale: "50 MP triple", camera_selfie: "12 MP", sim_slots: 2, os: "Android 14", nfc: true },
  "samsung|galaxy s24+": { processeur: "Snapdragon 8 Gen 3", ecran_pouces: "6.7\"", ecran_type: "Dynamic AMOLED 120Hz", batterie_mah: 4900, charge_w: 45, camera_principale: "50 MP triple", camera_selfie: "12 MP", sim_slots: 2, os: "Android 14", nfc: true },
  "samsung|galaxy s24 ultra": { processeur: "Snapdragon 8 Gen 3", ecran_pouces: "6.8\"", ecran_type: "Dynamic AMOLED 120Hz", batterie_mah: 5000, charge_w: 45, camera_principale: "200 MP quad", camera_selfie: "12 MP", sim_slots: 2, os: "Android 14", nfc: true },
  "samsung|galaxy a53": { processeur: "Exynos 1280", ecran_pouces: "6.5\"", ecran_type: "Super AMOLED 120Hz", batterie_mah: 5000, charge_w: 25, camera_principale: "64 MP quad", camera_selfie: "32 MP", sim_slots: 2, os: "Android 12", nfc: true },
  "samsung|galaxy a54": { processeur: "Exynos 1380", ecran_pouces: "6.4\"", ecran_type: "Super AMOLED 120Hz", batterie_mah: 5000, charge_w: 25, camera_principale: "50 MP triple", camera_selfie: "32 MP", sim_slots: 2, os: "Android 13", nfc: true },
  "samsung|galaxy a55": { processeur: "Exynos 1480", ecran_pouces: "6.6\"", ecran_type: "Super AMOLED 120Hz", batterie_mah: 5000, charge_w: 25, camera_principale: "50 MP triple", camera_selfie: "32 MP", sim_slots: 2, os: "Android 14", nfc: true },
  "samsung|galaxy a34": { processeur: "Dimensity 1080", ecran_pouces: "6.6\"", ecran_type: "Super AMOLED 120Hz", batterie_mah: 5000, charge_w: 25, camera_principale: "48 MP triple", camera_selfie: "13 MP", sim_slots: 2, os: "Android 13", nfc: true },
  "samsung|galaxy a35": { processeur: "Exynos 1380", ecran_pouces: "6.6\"", ecran_type: "Super AMOLED 120Hz", batterie_mah: 5000, charge_w: 25, camera_principale: "50 MP triple", camera_selfie: "13 MP", sim_slots: 2, os: "Android 14", nfc: true },
  "samsung|galaxy a15": { processeur: "Dimensity 6100+", ecran_pouces: "6.5\"", ecran_type: "Super AMOLED 90Hz", batterie_mah: 5000, charge_w: 25, camera_principale: "50 MP triple", camera_selfie: "13 MP", sim_slots: 2, os: "Android 14", nfc: false },
  "samsung|galaxy a25": { processeur: "Exynos 1280", ecran_pouces: "6.5\"", ecran_type: "Super AMOLED 120Hz", batterie_mah: 5000, charge_w: 25, camera_principale: "50 MP triple", camera_selfie: "13 MP", sim_slots: 2, os: "Android 14", nfc: true },
  "samsung|galaxy a05s": { processeur: "Snapdragon 680", ecran_pouces: "6.7\"", ecran_type: "PLS LCD 90Hz", batterie_mah: 5000, charge_w: 25, camera_principale: "50 MP triple", camera_selfie: "13 MP", sim_slots: 2, os: "Android 13", nfc: false },
  "samsung|galaxy s9+": { processeur: "Exynos 9810 / Snapdragon 845", ecran_pouces: "6.2\"", ecran_type: "Super AMOLED", batterie_mah: 3500, charge_w: 15, camera_principale: "12 MP double", camera_selfie: "8 MP", sim_slots: 2, os: "Android 8", nfc: true },
  "samsung|galaxy s10": { processeur: "Exynos 9820 / Snapdragon 855", ecran_pouces: "6.1\"", ecran_type: "Dynamic AMOLED", batterie_mah: 3400, charge_w: 15, camera_principale: "12 MP triple", camera_selfie: "10 MP", sim_slots: 2, os: "Android 9", nfc: true },
  "samsung|galaxy s10+": { processeur: "Exynos 9820 / Snapdragon 855", ecran_pouces: "6.4\"", ecran_type: "Dynamic AMOLED", batterie_mah: 4100, charge_w: 15, camera_principale: "12 MP triple", camera_selfie: "10 MP + 8 MP", sim_slots: 2, os: "Android 9", nfc: true },
  "samsung|galaxy s20": { processeur: "Exynos 990 / Snapdragon 865", ecran_pouces: "6.2\"", ecran_type: "Dynamic AMOLED 120Hz", batterie_mah: 4000, charge_w: 25, camera_principale: "64 MP triple", camera_selfie: "10 MP", sim_slots: 2, os: "Android 10", nfc: true },
  "samsung|galaxy s20+": { processeur: "Exynos 990 / Snapdragon 865", ecran_pouces: "6.7\"", ecran_type: "Dynamic AMOLED 120Hz", batterie_mah: 4500, charge_w: 25, camera_principale: "64 MP quad", camera_selfie: "10 MP", sim_slots: 2, os: "Android 10", nfc: true },
  "samsung|galaxy s20 fe": { processeur: "Exynos 990 / Snapdragon 865", ecran_pouces: "6.5\"", ecran_type: "Super AMOLED 120Hz", batterie_mah: 4500, charge_w: 25, camera_principale: "12 MP triple", camera_selfie: "32 MP", sim_slots: 2, os: "Android 10", nfc: true },

  // ── APPLE ──────────────────────────────────────────────────────────────────
  "apple|iphone 11": { processeur: "Apple A13 Bionic", ecran_pouces: "6.1\"", ecran_type: "IPS LCD", batterie_mah: 3110, charge_w: 18, camera_principale: "12 MP double", camera_selfie: "12 MP", sim_slots: 2, os: "iOS 13", nfc: true },
  "apple|iphone 12": { processeur: "Apple A14 Bionic", ecran_pouces: "6.1\"", ecran_type: "Super Retina OLED", batterie_mah: 2815, charge_w: 20, camera_principale: "12 MP double", camera_selfie: "12 MP", sim_slots: 2, os: "iOS 14", nfc: true },
  "apple|iphone 12 pro": { processeur: "Apple A14 Bionic", ecran_pouces: "6.1\"", ecran_type: "Super Retina OLED", batterie_mah: 2815, charge_w: 20, camera_principale: "12 MP triple LiDAR", camera_selfie: "12 MP", sim_slots: 2, os: "iOS 14", nfc: true },
  "apple|iphone 12 pro max": { processeur: "Apple A14 Bionic", ecran_pouces: "6.7\"", ecran_type: "Super Retina OLED", batterie_mah: 3687, charge_w: 20, camera_principale: "12 MP triple LiDAR", camera_selfie: "12 MP", sim_slots: 2, os: "iOS 14", nfc: true },
  "apple|iphone 13": { processeur: "Apple A15 Bionic", ecran_pouces: "6.1\"", ecran_type: "Super Retina OLED", batterie_mah: 3227, charge_w: 20, camera_principale: "12 MP double", camera_selfie: "12 MP", sim_slots: 2, os: "iOS 15", nfc: true },
  "apple|iphone 13 pro": { processeur: "Apple A15 Bionic", ecran_pouces: "6.1\"", ecran_type: "ProMotion OLED 120Hz", batterie_mah: 3095, charge_w: 27, camera_principale: "12 MP triple LiDAR", camera_selfie: "12 MP", sim_slots: 2, os: "iOS 15", nfc: true },
  "apple|iphone 13 pro max": { processeur: "Apple A15 Bionic", ecran_pouces: "6.7\"", ecran_type: "ProMotion OLED 120Hz", batterie_mah: 4352, charge_w: 27, camera_principale: "12 MP triple LiDAR", camera_selfie: "12 MP", sim_slots: 2, os: "iOS 15", nfc: true },
  "apple|iphone 14": { processeur: "Apple A15 Bionic", ecran_pouces: "6.1\"", ecran_type: "Super Retina OLED", batterie_mah: 3279, charge_w: 20, camera_principale: "12 MP double", camera_selfie: "12 MP", sim_slots: 2, os: "iOS 16", nfc: true },
  "apple|iphone 14 pro": { processeur: "Apple A16 Bionic", ecran_pouces: "6.1\"", ecran_type: "ProMotion OLED 120Hz", batterie_mah: 3200, charge_w: 27, camera_principale: "48 MP triple", camera_selfie: "12 MP", sim_slots: 2, os: "iOS 16", nfc: true },
  "apple|iphone 14 pro max": { processeur: "Apple A16 Bionic", ecran_pouces: "6.7\"", ecran_type: "ProMotion OLED 120Hz", batterie_mah: 4323, charge_w: 27, camera_principale: "48 MP triple", camera_selfie: "12 MP", sim_slots: 2, os: "iOS 16", nfc: true },
  "apple|iphone 15": { processeur: "Apple A16 Bionic", ecran_pouces: "6.1\"", ecran_type: "Super Retina OLED", batterie_mah: 3349, charge_w: 20, camera_principale: "48 MP double", camera_selfie: "12 MP", sim_slots: 2, os: "iOS 17", nfc: true },
  "apple|iphone 15 pro": { processeur: "Apple A17 Pro", ecran_pouces: "6.1\"", ecran_type: "ProMotion OLED 120Hz", batterie_mah: 3274, charge_w: 27, camera_principale: "48 MP triple", camera_selfie: "12 MP", sim_slots: 2, os: "iOS 17", nfc: true },
  "apple|iphone 15 pro max": { processeur: "Apple A17 Pro", ecran_pouces: "6.7\"", ecran_type: "ProMotion OLED 120Hz", batterie_mah: 4422, charge_w: 27, camera_principale: "48 MP triple", camera_selfie: "12 MP", sim_slots: 2, os: "iOS 17", nfc: true },

  // ── XIAOMI / REDMI ─────────────────────────────────────────────────────────
  "xiaomi|redmi note 12": { processeur: "Snapdragon 685", ecran_pouces: "6.67\"", ecran_type: "AMOLED 120Hz", batterie_mah: 5000, charge_w: 33, camera_principale: "50 MP triple", camera_selfie: "13 MP", sim_slots: 2, os: "Android 12", nfc: false },
  "xiaomi|redmi note 13": { processeur: "Snapdragon 685", ecran_pouces: "6.67\"", ecran_type: "AMOLED 120Hz", batterie_mah: 5000, charge_w: 33, camera_principale: "108 MP triple", camera_selfie: "16 MP", sim_slots: 2, os: "Android 13", nfc: false },
  "xiaomi|redmi note 13 pro": { processeur: "Dimensity 7200 Ultra", ecran_pouces: "6.67\"", ecran_type: "AMOLED 120Hz", batterie_mah: 5100, charge_w: 67, camera_principale: "200 MP triple", camera_selfie: "16 MP", sim_slots: 2, os: "Android 13", nfc: true },
  "xiaomi|redmi 12": { processeur: "Helio G88", ecran_pouces: "6.79\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 5000, charge_w: 18, camera_principale: "50 MP triple", camera_selfie: "8 MP", sim_slots: 2, os: "Android 13", nfc: false },
  "xiaomi|poco x5 pro": { processeur: "Snapdragon 778G", ecran_pouces: "6.67\"", ecran_type: "AMOLED 120Hz", batterie_mah: 5000, charge_w: 67, camera_principale: "108 MP triple", camera_selfie: "16 MP", sim_slots: 2, os: "Android 12", nfc: true },
  "xiaomi|poco x6 pro": { processeur: "Dimensity 8300 Ultra", ecran_pouces: "6.67\"", ecran_type: "AMOLED 144Hz", batterie_mah: 5000, charge_w: 67, camera_principale: "64 MP triple", camera_selfie: "20 MP", sim_slots: 2, os: "Android 14", nfc: true },

  // ── TECNO ──────────────────────────────────────────────────────────────────
  "tecno|tecno camon 11": { processeur: "Helio P22", ecran_pouces: "6.2\"", ecran_type: "IPS LCD", batterie_mah: 3750, charge_w: 10, camera_principale: "16 MP double", camera_selfie: "24 MP", sim_slots: 2, os: "Android 8.1", nfc: false },
  "tecno|tecno camon 12 air": { processeur: "Helio A22", ecran_pouces: "6.55\"", ecran_type: "IPS LCD", batterie_mah: 4000, charge_w: 10, camera_principale: "13 MP double", camera_selfie: "8 MP", sim_slots: 2, os: "Android 9", nfc: false },
  "tecno|tecno camon 15 air": { processeur: "Helio A25", ecran_pouces: "6.6\"", ecran_type: "IPS LCD", batterie_mah: 5000, charge_w: 18, camera_principale: "16 MP double", camera_selfie: "8 MP", sim_slots: 2, os: "Android 10", nfc: false },
  "tecno|tecno camon 16 s": { processeur: "Helio G80", ecran_pouces: "6.8\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 5000, charge_w: 18, camera_principale: "64 MP quad", camera_selfie: "16 MP", sim_slots: 2, os: "Android 10", nfc: false },
  "tecno|tecno camon 17p": { processeur: "Helio G85", ecran_pouces: "6.8\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 5000, charge_w: 18, camera_principale: "48 MP triple", camera_selfie: "48 MP", sim_slots: 2, os: "Android 11", nfc: false },
  "tecno|tecno camon 18 premier": { processeur: "Helio G96", ecran_pouces: "6.7\"", ecran_type: "AMOLED 120Hz", batterie_mah: 4750, charge_w: 33, camera_principale: "64 MP triple", camera_selfie: "32 MP", sim_slots: 2, os: "Android 11", nfc: false },
  "tecno|tecno camon 18i": { processeur: "Helio G85", ecran_pouces: "6.8\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 5000, charge_w: 18, camera_principale: "13 MP triple", camera_selfie: "8 MP", sim_slots: 2, os: "Android 11", nfc: false },
  "tecno|tecno camon 19 neo": { processeur: "Helio G85", ecran_pouces: "6.8\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 5000, charge_w: 18, camera_principale: "48 MP triple", camera_selfie: "16 MP", sim_slots: 2, os: "Android 12", nfc: false },
  "tecno|tecno camon 19 pro": { processeur: "Helio G96", ecran_pouces: "6.8\"", ecran_type: "AMOLED 120Hz", batterie_mah: 5000, charge_w: 33, camera_principale: "64 MP triple", camera_selfie: "32 MP", sim_slots: 2, os: "Android 12", nfc: false },
  "tecno|tecno camon 20": { processeur: "Helio G85", ecran_pouces: "6.67\"", ecran_type: "AMOLED 60Hz", batterie_mah: 5000, charge_w: 18, camera_principale: "64 MP triple", camera_selfie: "32 MP", sim_slots: 2, os: "Android 13", nfc: false },
  "tecno|tecno camon 20 premier": { processeur: "Dimensity 8050", ecran_pouces: "6.67\"", ecran_type: "AMOLED 144Hz", batterie_mah: 5000, charge_w: 45, camera_principale: "50 MP triple", camera_selfie: "50 MP", sim_slots: 2, os: "Android 13", nfc: false },
  "tecno|tecno camon 20 pro": { processeur: "Helio G99", ecran_pouces: "6.67\"", ecran_type: "AMOLED 120Hz", batterie_mah: 5000, charge_w: 33, camera_principale: "64 MP triple", camera_selfie: "32 MP", sim_slots: 2, os: "Android 13", nfc: false },
  "tecno|tecno camon 30": { processeur: "Dimensity 6080", ecran_pouces: "6.78\"", ecran_type: "AMOLED 144Hz", batterie_mah: 5000, charge_w: 45, camera_principale: "50 MP triple", camera_selfie: "32 MP", sim_slots: 2, os: "Android 14", nfc: false },
  "tecno|tecno camon 30 pro": { processeur: "Dimensity 7300 Ultimate", ecran_pouces: "6.78\"", ecran_type: "AMOLED 144Hz", batterie_mah: 5000, charge_w: 70, camera_principale: "50 MP triple", camera_selfie: "50 MP", sim_slots: 2, os: "Android 14", nfc: false },
  "tecno|tecno camon 30s pro": { processeur: "Dimensity 7300 Ultimate", ecran_pouces: "6.78\"", ecran_type: "AMOLED 144Hz", batterie_mah: 5200, charge_w: 70, camera_principale: "50 MP triple", camera_selfie: "50 MP", sim_slots: 2, os: "Android 14", nfc: false },
  "tecno|tecno camon 40": { processeur: "Helio G100 Ultimate", ecran_pouces: "6.78\"", ecran_type: "AMOLED 144Hz", batterie_mah: 5200, charge_w: 45, camera_principale: "50 MP triple", camera_selfie: "50 MP", sim_slots: 2, os: "Android 15", nfc: false },
  "tecno|tecno camon 40 pro": { processeur: "Dimensity 7300", ecran_pouces: "6.78\"", ecran_type: "AMOLED 144Hz", batterie_mah: 5200, charge_w: 68, camera_principale: "50 MP triple", camera_selfie: "50 MP", sim_slots: 2, os: "Android 15", nfc: true },
  "tecno|camon 50": { processeur: "Dimensity 7300 Ultimate", ecran_pouces: "6.78\"", ecran_type: "AMOLED 144Hz", batterie_mah: 5200, charge_w: 68, camera_principale: "50 MP triple", camera_selfie: "50 MP", sim_slots: 2, os: "Android 15", nfc: false },
  "tecno|camon 50 pro 5g": { processeur: "Dimensity 7300 Ultimate", ecran_pouces: "6.78\"", ecran_type: "AMOLED 144Hz", batterie_mah: 5200, charge_w: 68, camera_principale: "50 MP triple", camera_selfie: "50 MP", sim_slots: 2, os: "Android 15", nfc: true },
  "tecno|spark slim": { processeur: "Dimensity 6300", ecran_pouces: "6.78\"", ecran_type: "AMOLED 120Hz", batterie_mah: 4600, charge_w: 33, camera_principale: "50 MP double", camera_selfie: "16 MP", sim_slots: 2, os: "Android 14", nfc: false },
  "tecno|tecno spark 40": { processeur: "Helio G99", ecran_pouces: "6.78\"", ecran_type: "AMOLED 120Hz", batterie_mah: 5000, charge_w: 33, camera_principale: "50 MP double", camera_selfie: "16 MP", sim_slots: 2, os: "Android 15", nfc: false },
  "tecno|tecno spark 40 pro": { processeur: "Helio G100 Ultimate", ecran_pouces: "6.78\"", ecran_type: "AMOLED 144Hz", batterie_mah: 5200, charge_w: 45, camera_principale: "50 MP double", camera_selfie: "13 MP", sim_slots: 2, os: "Android 15", nfc: false },
  "tecno|tecno spark 40c": { processeur: "Helio G81", ecran_pouces: "6.67\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 6000, charge_w: 18, camera_principale: "50 MP double", camera_selfie: "8 MP", sim_slots: 2, os: "Android 15", nfc: false },
  "tecno|tecno spark 30c": { processeur: "Helio G88", ecran_pouces: "6.78\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 5000, charge_w: 18, camera_principale: "50 MP double", camera_selfie: "8 MP", sim_slots: 2, os: "Android 14", nfc: false },
  "tecno|tecno spark 30 pro": { processeur: "Helio G99", ecran_pouces: "6.78\"", ecran_type: "AMOLED 120Hz", batterie_mah: 5000, charge_w: 33, camera_principale: "50 MP double", camera_selfie: "32 MP", sim_slots: 2, os: "Android 14", nfc: false },
  "tecno|tecno spark 20 pro+": { processeur: "Helio G99", ecran_pouces: "6.78\"", ecran_type: "AMOLED 120Hz", batterie_mah: 5000, charge_w: 33, camera_principale: "108 MP double", camera_selfie: "32 MP", sim_slots: 2, os: "Android 13", nfc: false },
  "tecno|tecno spark go 1": { processeur: "Helio G36", ecran_pouces: "6.56\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 5000, charge_w: 10, camera_principale: "13 MP double", camera_selfie: "5 MP", sim_slots: 2, os: "Android 14", nfc: false },
  "tecno|pova 7 5g": { processeur: "Dimensity 6300", ecran_pouces: "6.78\"", ecran_type: "IPS LCD 120Hz", batterie_mah: 6000, charge_w: 45, camera_principale: "50 MP double", camera_selfie: "16 MP", sim_slots: 2, os: "Android 14", nfc: false },
  "tecno|pova 7 pro 5g": { processeur: "Dimensity 7300 Ultimate", ecran_pouces: "6.78\"", ecran_type: "AMOLED 144Hz", batterie_mah: 6000, charge_w: 68, camera_principale: "50 MP triple", camera_selfie: "32 MP", sim_slots: 2, os: "Android 14", nfc: false },
  "tecno|pova slim 5g": { processeur: "Dimensity 6300", ecran_pouces: "6.67\"", ecran_type: "AMOLED 120Hz", batterie_mah: 4600, charge_w: 33, camera_principale: "50 MP double", camera_selfie: "16 MP", sim_slots: 2, os: "Android 14", nfc: false },
  "tecno|tecno pova 3": { processeur: "Helio G88", ecran_pouces: "6.9\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 7000, charge_w: 33, camera_principale: "50 MP triple", camera_selfie: "8 MP", sim_slots: 2, os: "Android 12", nfc: false },
  "tecno|tecno pova 4 pro": { processeur: "Helio G99", ecran_pouces: "6.78\"", ecran_type: "IPS LCD 120Hz", batterie_mah: 6000, charge_w: 33, camera_principale: "50 MP triple", camera_selfie: "32 MP", sim_slots: 2, os: "Android 12", nfc: false },
  "tecno|tecno pova 6": { processeur: "Helio G99 Ultimate", ecran_pouces: "6.78\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 6000, charge_w: 33, camera_principale: "50 MP double", camera_selfie: "16 MP", sim_slots: 2, os: "Android 14", nfc: false },
  "tecno|tecno pova 6 neo": { processeur: "Helio G99 Ultimate", ecran_pouces: "6.78\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 7000, charge_w: 18, camera_principale: "50 MP double", camera_selfie: "8 MP", sim_slots: 2, os: "Android 14", nfc: false },
  "tecno|tecno pova 6 neo 5g": { processeur: "Dimensity 6300", ecran_pouces: "6.78\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 6000, charge_w: 18, camera_principale: "50 MP double", camera_selfie: "8 MP", sim_slots: 2, os: "Android 14", nfc: false },
  "tecno|tecno pova neo": { processeur: "Helio G25", ecran_pouces: "6.8\"", ecran_type: "IPS LCD", batterie_mah: 6000, charge_w: 18, camera_principale: "13 MP triple", camera_selfie: "8 MP", sim_slots: 2, os: "Android 11", nfc: false },
  "tecno|tecno pova neo 2": { processeur: "Helio G85", ecran_pouces: "6.82\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 6000, charge_w: 18, camera_principale: "50 MP triple", camera_selfie: "8 MP", sim_slots: 2, os: "Android 12", nfc: false },
  "tecno|tecno pova neo 3": { processeur: "Helio G85", ecran_pouces: "6.78\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 6000, charge_w: 18, camera_principale: "50 MP double", camera_selfie: "8 MP", sim_slots: 2, os: "Android 13", nfc: false },
  "tecno|tecno pova neo 5g": { processeur: "Dimensity 810", ecran_pouces: "6.8\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 5000, charge_w: 18, camera_principale: "50 MP triple", camera_selfie: "8 MP", sim_slots: 2, os: "Android 12", nfc: false },
  "tecno|tecno phantom x2": { processeur: "Dimensity 9000", ecran_pouces: "6.8\"", ecran_type: "AMOLED 120Hz", batterie_mah: 5160, charge_w: 45, camera_principale: "64 MP triple", camera_selfie: "32 MP", sim_slots: 2, os: "Android 12", nfc: false },
  "tecno|tecno phantom v fold": { processeur: "Dimensity 9000+", ecran_pouces: "7.85\" + 6.42\"", ecran_type: "AMOLED 120Hz", batterie_mah: 5000, charge_w: 45, camera_principale: "50 MP triple", camera_selfie: "16 MP", sim_slots: 2, os: "Android 13", nfc: false },
  "tecno|tecno phantom v fold2": { processeur: "Dimensity 9200+", ecran_pouces: "7.85\" + 6.42\"", ecran_type: "AMOLED 120Hz", batterie_mah: 5000, charge_w: 68, camera_principale: "50 MP triple", camera_selfie: "32 MP", sim_slots: 2, os: "Android 14", nfc: false },
  "tecno|tecno phantom v flip": { processeur: "Dimensity 8050", ecran_pouces: "6.9\" + 1.32\"", ecran_type: "AMOLED 120Hz", batterie_mah: 4000, charge_w: 45, camera_principale: "64 MP double", camera_selfie: "16 MP", sim_slots: 2, os: "Android 13", nfc: false },
  "tecno|tecno phantom v flip2": { processeur: "Dimensity 8200", ecran_pouces: "6.9\" + 1.32\"", ecran_type: "AMOLED 120Hz", batterie_mah: 4000, charge_w: 45, camera_principale: "50 MP double", camera_selfie: "16 MP", sim_slots: 2, os: "Android 14", nfc: false },
  "tecno|tecno phantom 9": { processeur: "Helio P35", ecran_pouces: "6.4\"", ecran_type: "IPS LCD", batterie_mah: 3500, charge_w: 18, camera_principale: "48 MP triple", camera_selfie: "32 MP", sim_slots: 2, os: "Android 9", nfc: false },
  "tecno|pop x": { processeur: "Helio G85", ecran_pouces: "6.78\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 5000, charge_w: 18, camera_principale: "50 MP double", camera_selfie: "8 MP", sim_slots: 2, os: "Android 15", nfc: false },

  // ── INFINIX ────────────────────────────────────────────────────────────────
  "infinix|hot 40": { processeur: "Helio G88", ecran_pouces: "6.78\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 5000, charge_w: 18, camera_principale: "50 MP double", camera_selfie: "8 MP", sim_slots: 2, os: "Android 13", nfc: false },
  "infinix|hot 40i": { processeur: "Helio G85", ecran_pouces: "6.56\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 5000, charge_w: 18, camera_principale: "50 MP double", camera_selfie: "8 MP", sim_slots: 2, os: "Android 13", nfc: false },
  "infinix|hot 40 pro": { processeur: "Helio G99", ecran_pouces: "6.78\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 5000, charge_w: 33, camera_principale: "108 MP triple", camera_selfie: "32 MP", sim_slots: 2, os: "Android 13", nfc: false },
  "infinix|hot 50": { processeur: "Dimensity 6300", ecran_pouces: "6.7\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 5000, charge_w: 18, camera_principale: "50 MP double", camera_selfie: "8 MP", sim_slots: 2, os: "Android 14", nfc: false },
  "infinix|hot 50 pro": { processeur: "Helio G100", ecran_pouces: "6.78\"", ecran_type: "AMOLED 120Hz", batterie_mah: 5000, charge_w: 33, camera_principale: "50 MP triple", camera_selfie: "16 MP", sim_slots: 2, os: "Android 14", nfc: true },
  "infinix|hot 50 pro+": { processeur: "Helio G100", ecran_pouces: "6.78\"", ecran_type: "AMOLED 120Hz", batterie_mah: 5000, charge_w: 33, camera_principale: "108 MP triple", camera_selfie: "32 MP", sim_slots: 2, os: "Android 14", nfc: true },
  "infinix|note 30": { processeur: "Helio G99", ecran_pouces: "6.78\"", ecran_type: "AMOLED 120Hz", batterie_mah: 5000, charge_w: 45, camera_principale: "108 MP triple", camera_selfie: "32 MP", sim_slots: 2, os: "Android 13", nfc: true },
  "infinix|note 30 5g": { processeur: "Dimensity 6080", ecran_pouces: "6.78\"", ecran_type: "AMOLED 120Hz", batterie_mah: 5000, charge_w: 45, camera_principale: "108 MP triple", camera_selfie: "16 MP", sim_slots: 2, os: "Android 13", nfc: true },
  "infinix|note 40": { processeur: "Helio G99 Ultimate", ecran_pouces: "6.78\"", ecran_type: "AMOLED 144Hz", batterie_mah: 5000, charge_w: 70, camera_principale: "108 MP triple", camera_selfie: "32 MP", sim_slots: 2, os: "Android 14", nfc: true },
  "infinix|note 40 pro": { processeur: "Dimensity 7020", ecran_pouces: "6.78\"", ecran_type: "AMOLED 144Hz", batterie_mah: 5000, charge_w: 100, camera_principale: "108 MP triple", camera_selfie: "32 MP", sim_slots: 2, os: "Android 14", nfc: true },
  "infinix|note 50": { processeur: "Helio G100 Ultimate", ecran_pouces: "6.78\"", ecran_type: "AMOLED 144Hz", batterie_mah: 5200, charge_w: 68, camera_principale: "108 MP triple", camera_selfie: "32 MP", sim_slots: 2, os: "Android 15", nfc: true },
  "infinix|note 50 pro": { processeur: "Helio G100 Ultimate", ecran_pouces: "6.78\"", ecran_type: "AMOLED 144Hz", batterie_mah: 5200, charge_w: 90, camera_principale: "108 MP triple", camera_selfie: "32 MP", sim_slots: 2, os: "Android 15", nfc: true },
  "infinix|note 50 pro+": { processeur: "Dimensity 8350 Ultimate", ecran_pouces: "6.78\"", ecran_type: "AMOLED 144Hz", batterie_mah: 5200, charge_w: 100, camera_principale: "108 MP triple", camera_selfie: "50 MP", sim_slots: 2, os: "Android 15", nfc: true },
  "infinix|note 50x": { processeur: "Dimensity 7300 Ultimate", ecran_pouces: "6.78\"", ecran_type: "AMOLED 144Hz", batterie_mah: 5200, charge_w: 68, camera_principale: "108 MP triple", camera_selfie: "32 MP", sim_slots: 2, os: "Android 15", nfc: true },
  "infinix|smart 9": { processeur: "Helio G36", ecran_pouces: "6.6\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 5000, charge_w: 10, camera_principale: "13 MP double", camera_selfie: "5 MP", sim_slots: 2, os: "Android 13", nfc: false },
  "infinix|zero 30": { processeur: "Dimensity 8020", ecran_pouces: "6.78\"", ecran_type: "AMOLED 144Hz", batterie_mah: 5000, charge_w: 68, camera_principale: "108 MP triple", camera_selfie: "50 MP", sim_slots: 2, os: "Android 13", nfc: true },
  "infinix|zero 40": { processeur: "Dimensity 8200 Ultra", ecran_pouces: "6.78\"", ecran_type: "AMOLED 144Hz", batterie_mah: 5000, charge_w: 68, camera_principale: "50 MP triple", camera_selfie: "50 MP", sim_slots: 2, os: "Android 14", nfc: true },
  "infinix|gt 20 pro": { processeur: "Dimensity 8200 Ultimate", ecran_pouces: "6.67\"", ecran_type: "AMOLED 144Hz", batterie_mah: 5000, charge_w: 68, camera_principale: "108 MP triple", camera_selfie: "16 MP", sim_slots: 2, os: "Android 14", nfc: true },
  "infinix|infinix note 12": { processeur: "Helio G88", ecran_pouces: "6.7\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 5000, charge_w: 33, camera_principale: "50 MP triple", camera_selfie: "16 MP", sim_slots: 2, os: "Android 12", nfc: false },
  "infinix|infinix note 12 5g": { processeur: "Dimensity 810", ecran_pouces: "6.7\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 5000, charge_w: 33, camera_principale: "50 MP triple", camera_selfie: "8 MP", sim_slots: 2, os: "Android 12", nfc: false },
  "infinix|infinix note 30 5g": { processeur: "Dimensity 6080", ecran_pouces: "6.78\"", ecran_type: "AMOLED 120Hz", batterie_mah: 5000, charge_w: 45, camera_principale: "108 MP triple", camera_selfie: "16 MP", sim_slots: 2, os: "Android 13", nfc: true },

  // ── ITEL ───────────────────────────────────────────────────────────────────
  "itel|itel a70": { processeur: "Unisoc SC9863A2", ecran_pouces: "6.6\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 5000, charge_w: 10, camera_principale: "8 MP double", camera_selfie: "5 MP", sim_slots: 2, os: "Android 13", nfc: false },
  "itel|itel a80": { processeur: "Unisoc T606", ecran_pouces: "6.6\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 5000, charge_w: 18, camera_principale: "50 MP double", camera_selfie: "8 MP", sim_slots: 2, os: "Android 14", nfc: false },
  "itel|itel p55": { processeur: "Unisoc T606", ecran_pouces: "6.6\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 6000, charge_w: 18, camera_principale: "13 MP double", camera_selfie: "8 MP", sim_slots: 2, os: "Android 13", nfc: false },
  "itel|p55": { processeur: "Unisoc T606", ecran_pouces: "6.6\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 6000, charge_w: 18, camera_principale: "13 MP double", camera_selfie: "8 MP", sim_slots: 2, os: "Android 14", nfc: false },
  "itel|p55+": { processeur: "Unisoc T616", ecran_pouces: "6.6\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 6000, charge_w: 33, camera_principale: "50 MP double", camera_selfie: "8 MP", sim_slots: 2, os: "Android 14", nfc: false },
  "itel|itel p55 5g": { processeur: "Dimensity 6100+", ecran_pouces: "6.6\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 6000, charge_w: 18, camera_principale: "50 MP double", camera_selfie: "8 MP", sim_slots: 2, os: "Android 13", nfc: false },
  "itel|itel p65": { processeur: "Unisoc T616", ecran_pouces: "6.78\"", ecran_type: "IPS LCD 90Hz", batterie_mah: 6000, charge_w: 18, camera_principale: "50 MP double", camera_selfie: "8 MP", sim_slots: 2, os: "Android 14", nfc: false },
  "itel|itel s23": { processeur: "Unisoc T616", ecran_pouces: "6.78\"", ecran_type: "AMOLED 90Hz", batterie_mah: 5000, charge_w: 33, camera_principale: "50 MP double", camera_selfie: "16 MP", sim_slots: 2, os: "Android 13", nfc: false },
  "itel|itel s24": { processeur: "Unisoc T616", ecran_pouces: "6.78\"", ecran_type: "AMOLED 90Hz", batterie_mah: 5000, charge_w: 33, camera_principale: "50 MP double", camera_selfie: "32 MP", sim_slots: 2, os: "Android 14", nfc: false },
  "itel|s24": { processeur: "Unisoc T616", ecran_pouces: "6.78\"", ecran_type: "AMOLED 90Hz", batterie_mah: 5000, charge_w: 33, camera_principale: "50 MP double", camera_selfie: "32 MP", sim_slots: 2, os: "Android 14", nfc: false },
  "itel|itel s25": { processeur: "Unisoc T620", ecran_pouces: "6.78\"", ecran_type: "AMOLED 120Hz", batterie_mah: 5000, charge_w: 33, camera_principale: "50 MP double", camera_selfie: "32 MP", sim_slots: 2, os: "Android 14", nfc: false },
  "itel|itel s25 ultra": { processeur: "Unisoc T620", ecran_pouces: "6.78\"", ecran_type: "AMOLED 120Hz", batterie_mah: 5000, charge_w: 33, camera_principale: "50 MP triple", camera_selfie: "50 MP", sim_slots: 2, os: "Android 14", nfc: false },
  "itel|itel s18": { processeur: "Unisoc T606", ecran_pouces: "6.78\"", ecran_type: "AMOLED 90Hz", batterie_mah: 5000, charge_w: 18, camera_principale: "50 MP double", camera_selfie: "8 MP", sim_slots: 2, os: "Android 12", nfc: false },
  "itel|itel s18 pro": { processeur: "Unisoc T606", ecran_pouces: "6.78\"", ecran_type: "AMOLED 90Hz", batterie_mah: 5000, charge_w: 18, camera_principale: "50 MP double", camera_selfie: "16 MP", sim_slots: 2, os: "Android 13", nfc: false },

  // ── SAMSUNG (nouvelles séries) ─────────────────────────────────────────────
  "samsung|samsung galaxy s25": { processeur: "Snapdragon 8 Elite", ecran_pouces: "6.2\"", ecran_type: "Dynamic AMOLED 120Hz", batterie_mah: 4000, charge_w: 25, camera_principale: "50 MP triple", camera_selfie: "12 MP", sim_slots: 2, os: "Android 15", nfc: true },
  "samsung|samsung galaxy s25+": { processeur: "Snapdragon 8 Elite", ecran_pouces: "6.7\"", ecran_type: "Dynamic AMOLED 120Hz LTPO", batterie_mah: 4900, charge_w: 45, camera_principale: "50 MP triple", camera_selfie: "12 MP", sim_slots: 2, os: "Android 15", nfc: true },
  "samsung|samsung galaxy s25 ultra": { processeur: "Snapdragon 8 Elite", ecran_pouces: "6.9\"", ecran_type: "Dynamic AMOLED 120Hz", batterie_mah: 5000, charge_w: 45, camera_principale: "200 MP quad", camera_selfie: "12 MP", sim_slots: 2, os: "Android 15", nfc: true },
  "samsung|samsung galaxy a16": { processeur: "Helio G99", ecran_pouces: "6.7\"", ecran_type: "Super AMOLED 90Hz", batterie_mah: 5000, charge_w: 25, camera_principale: "50 MP triple", camera_selfie: "13 MP", sim_slots: 2, os: "Android 14", nfc: false },
  "samsung|samsung galaxy a16 5g": { processeur: "Exynos 1330", ecran_pouces: "6.7\"", ecran_type: "Super AMOLED 90Hz", batterie_mah: 5000, charge_w: 25, camera_principale: "50 MP triple", camera_selfie: "13 MP", sim_slots: 2, os: "Android 14", nfc: true },
  "samsung|samsung galaxy a26": { processeur: "Exynos 1380", ecran_pouces: "6.7\"", ecran_type: "Super AMOLED 120Hz", batterie_mah: 5000, charge_w: 25, camera_principale: "50 MP triple", camera_selfie: "13 MP", sim_slots: 2, os: "Android 15", nfc: true },
  "samsung|samsung galaxy a56": { processeur: "Exynos 1580", ecran_pouces: "6.7\"", ecran_type: "Super AMOLED 120Hz", batterie_mah: 5000, charge_w: 45, camera_principale: "50 MP triple", camera_selfie: "12 MP", sim_slots: 2, os: "Android 15", nfc: true },
  "samsung|samsung galaxy m35": { processeur: "Exynos 1380", ecran_pouces: "6.6\"", ecran_type: "Super AMOLED 120Hz", batterie_mah: 6000, charge_w: 25, camera_principale: "50 MP triple", camera_selfie: "13 MP", sim_slots: 2, os: "Android 14", nfc: true },
  "samsung|samsung galaxy m55": { processeur: "Snapdragon 7 Gen 1", ecran_pouces: "6.7\"", ecran_type: "Super AMOLED 120Hz", batterie_mah: 5000, charge_w: 45, camera_principale: "50 MP triple", camera_selfie: "50 MP", sim_slots: 2, os: "Android 14", nfc: true },

  // ── XIAOMI / REDMI / POCO (nouvelles séries) ────────────────────────────────
  "xiaomi|xiaomi 14t": { processeur: "Dimensity 8300 Ultra", ecran_pouces: "6.67\"", ecran_type: "AMOLED 144Hz", batterie_mah: 5000, charge_w: 67, camera_principale: "50 MP triple", camera_selfie: "32 MP", sim_slots: 2, os: "Android 14", nfc: true },
  "xiaomi|xiaomi 14t pro": { processeur: "Dimensity 9300+", ecran_pouces: "6.67\"", ecran_type: "AMOLED 144Hz", batterie_mah: 5000, charge_w: 120, camera_principale: "50 MP triple", camera_selfie: "32 MP", sim_slots: 2, os: "Android 14", nfc: true },
  "xiaomi|redmi note 14": { processeur: "Snapdragon 7s Gen 3", ecran_pouces: "6.67\"", ecran_type: "AMOLED 120Hz", batterie_mah: 5110, charge_w: 45, camera_principale: "108 MP triple", camera_selfie: "20 MP", sim_slots: 2, os: "Android 14", nfc: true },
  "xiaomi|redmi note 14 pro": { processeur: "Dimensity 7300 Ultra", ecran_pouces: "6.67\"", ecran_type: "AMOLED 120Hz", batterie_mah: 5110, charge_w: 67, camera_principale: "200 MP triple", camera_selfie: "20 MP", sim_slots: 2, os: "Android 14", nfc: true },
  "xiaomi|redmi note 14 pro+": { processeur: "Dimensity 7300 Ultra", ecran_pouces: "6.67\"", ecran_type: "AMOLED 120Hz", batterie_mah: 5110, charge_w: 90, camera_principale: "200 MP triple", camera_selfie: "20 MP", sim_slots: 2, os: "Android 14", nfc: true },
  "poco|x8 pro max 5g": { processeur: "Dimensity 8500 Ultra", ecran_pouces: "6.59\"", ecran_type: "AMOLED 144Hz", batterie_mah: 6500, charge_w: 100, camera_principale: "50 MP triple", camera_selfie: "20 MP", sim_slots: 2, os: "Android 15", nfc: true },
  "poco|poco x6 pro": { processeur: "Dimensity 8300 Ultra", ecran_pouces: "6.67\"", ecran_type: "AMOLED 144Hz", batterie_mah: 5000, charge_w: 67, camera_principale: "64 MP triple", camera_selfie: "20 MP", sim_slots: 2, os: "Android 14", nfc: true },

  // ── OPPO ───────────────────────────────────────────────────────────────────
  "oppo|reno 10": { processeur: "Snapdragon 778G", ecran_pouces: "6.7\"", ecran_type: "AMOLED 120Hz", batterie_mah: 5000, charge_w: 67, camera_principale: "64 MP triple", camera_selfie: "32 MP", sim_slots: 2, os: "Android 13", nfc: true },
  "oppo|reno 11": { processeur: "Dimensity 7050", ecran_pouces: "6.7\"", ecran_type: "AMOLED 120Hz", batterie_mah: 4800, charge_w: 67, camera_principale: "50 MP triple", camera_selfie: "32 MP", sim_slots: 2, os: "Android 14", nfc: true },
  "oppo|a98": { processeur: "Snapdragon 695", ecran_pouces: "6.72\"", ecran_type: "IPS LCD 120Hz", batterie_mah: 5000, charge_w: 67, camera_principale: "64 MP double", camera_selfie: "32 MP", sim_slots: 2, os: "Android 13", nfc: false },

  "oppo|realme 13 pro": { processeur: "Snapdragon 7s Gen 2", ecran_pouces: "6.7\"", ecran_type: "AMOLED 120Hz", batterie_mah: 5000, charge_w: 45, camera_principale: "50 MP triple", camera_selfie: "16 MP", sim_slots: 2, os: "Android 14", nfc: true },
  "oppo|realme 13 pro+": { processeur: "Dimensity 7300 Energy", ecran_pouces: "6.7\"", ecran_type: "AMOLED 120Hz", batterie_mah: 5200, charge_w: 80, camera_principale: "50 MP triple", camera_selfie: "32 MP", sim_slots: 2, os: "Android 14", nfc: true },

  // ── VIVO ───────────────────────────────────────────────────────────────────
  "vivo|v29": { processeur: "Snapdragon 778G", ecran_pouces: "6.78\"", ecran_type: "AMOLED 120Hz", batterie_mah: 4600, charge_w: 80, camera_principale: "50 MP triple", camera_selfie: "50 MP", sim_slots: 2, os: "Android 13", nfc: true },
  "vivo|v30": { processeur: "Snapdragon 7 Gen 3", ecran_pouces: "6.78\"", ecran_type: "AMOLED 120Hz", batterie_mah: 5000, charge_w: 80, camera_principale: "50 MP triple", camera_selfie: "50 MP", sim_slots: 2, os: "Android 14", nfc: true },
  "vivo|v50": { processeur: "Snapdragon 7 Gen 3", ecran_pouces: "6.77\"", ecran_type: "AMOLED 120Hz", batterie_mah: 6500, charge_w: 90, camera_principale: "50 MP double", camera_selfie: "50 MP", sim_slots: 2, os: "Android 15", nfc: true },
  "vivo|v60": { processeur: "Snapdragon 7s Gen 3", ecran_pouces: "6.67\"", ecran_type: "AMOLED 120Hz", batterie_mah: 5500, charge_w: 80, camera_principale: "50 MP triple", camera_selfie: "50 MP", sim_slots: 2, os: "Android 15", nfc: true },
  "vivo|t4 ultra": { processeur: "Dimensity 9300+", ecran_pouces: "6.78\"", ecran_type: "AMOLED 144Hz", batterie_mah: 6500, charge_w: 90, camera_principale: "50 MP triple", camera_selfie: "32 MP", sim_slots: 2, os: "Android 15", nfc: true },
  "vivo|y300 pro": { processeur: "Snapdragon 695", ecran_pouces: "6.78\"", ecran_type: "AMOLED 120Hz", batterie_mah: 6000, charge_w: 44, camera_principale: "50 MP double", camera_selfie: "16 MP", sim_slots: 2, os: "Android 14", nfc: false },
  "vivo|v70 fe": { processeur: "Dimensity 7300 Ultra", ecran_pouces: "6.78\"", ecran_type: "AMOLED 120Hz", batterie_mah: 5500, charge_w: 80, camera_principale: "50 MP triple", camera_selfie: "50 MP", sim_slots: 2, os: "Android 15", nfc: true },
};

export function getPhoneSpecs(marque: string, modele: string): PhoneSpecSheet {
  const normalize = (s: string) => s.toLowerCase().trim().replace(/\s+/g, " ");
  const key = `${normalize(marque)}|${normalize(modele)}`;
  return SPECS[key] ?? {};
}
